### ISSUE TITLE
Cleanup JS in boiler-plate HTML

### ISSUE THREAD

**Issue by angadgill** [angadgill/python-web-analytics#4]
So that it no longer uses Google Analytics object

**Comment by angadgill** [comment]
Fetch JS from this location: http://cdn.pywebanalytics.org/pwanalytics.js

**Comment by angadgill** [comment]
Remove Google Analytics object from here too: https://github.com/angadgill/python-web-analytics/blob/gh-pages/_includes/page-footer.html#L5

**Comment by b-huynh** [comment]
Done.

See 7d10f3e3cf132ebebbceb6391af9282f6d9295a7 and 3390191d5c662c1392991d9542ed87f5865cc4dd
